[package]
name = "pcap2socks"
version = "0.1.0"
authors = ["Xie Zhihao <xzh1206@gmail.com>"]
edition = "2018"
description = "Redirect traffic to SOCKS proxy with pcap."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-socks5 = "0.3.1"
clap = "3.0.0-beta.1"
env_logger = "0.7.1"
ipnetwork = "0.16.0"
log = "0.4.8"
lru = "0.5.2"
pnet = "0.26.0"
socks = "0.3.2"
tokio = { version = "0.2.21", features = ["macros", "rt-core", "rt-threaded", "tcp", "time", "udp"] }
